class IDigitalDiscovery:
    PATHNAME: str = 'sso/oidc/.well-known/openid-configuration'

    def __init__(self, discovery: dict):
        self.issuer: str = discovery.get('issuer', None)
        self.jwks_uri: str = discovery.get('jwks_uri', None)
        self.token_endpoint: str = discovery.get('token_endpoint', None)
        self.claims_supported: tuple = discovery.get('claims_supported', None)
        self.scopes_supported: tuple = discovery.get('scopes_supported', None)
        self.end_session_endpoint: str = discovery.get('end_session_endpoint', None)
        self.userinfo_endpoint: str | None = discovery.get('userinfo_endpoint', None)
        self.claim_types_supported: tuple = discovery.get('claim_types_supported', None)
        self.grant_types_supported: tuple = discovery.get('grant_types_supported', None)
        self.authorization_endpoint: str = discovery.get('authorization_endpoint', None)
        self.subject_types_supported: tuple = discovery.get('subject_types_supported', None)
        self.response_modes_supported: tuple = discovery.get('response_modes_supported', None)
        self.response_types_supported: tuple = discovery.get('response_types_supported', None)
        self.claims_parameter_supported: bool = discovery.get('claims_parameter_supported', False)
        self.request_parameter_supported: bool = discovery.get('request_parameter_supported', False)
        self.backchannel_logout_supported: bool = discovery.get('backchannel_logout_supported', False)
        self.request_uri_parameter_supported: bool = discovery.get('request_uri_parameter_supported', False)
        self.require_request_uri_registration: bool = discovery.get('require_request_uri_registration', False)
        self.code_challenge_methods_supported: tuple = discovery.get('code_challenge_methods_supported', None)
        self.dpop_signing_alg_values_supported: tuple = discovery.get('dpop_signing_alg_values_supported', None)
        self.backchannel_logout_session_supported: bool = discovery.get('backchannel_logout_session_supported', False)
        self.id_token_signing_alg_values_supported: tuple = discovery.get('id_token_signing_alg_values_supported', None)
        self.token_endpoint_auth_methods_supported: tuple = discovery.get('token_endpoint_auth_methods_supported', None)
        self.request_object_signing_alg_values_supported: tuple = discovery.get('request_object_signing_alg_values_supported', None)
        self.authorization_response_iss_parameter_supported: bool = discovery.get('authorization_response_iss_parameter_supported', False)
